---
header: |
  # frozen_string_literal: true

  require 'simplecov'

  ::SimpleCov.command_name 'Brutal test suite'
  ::SimpleCov.start

  require './lib/brutal/scaffold'

subject: |
  ::Brutal::Scaffold.new("%{header}", '%{subject}', *%{actuals}, **%{contexts})

contexts:
  :header:
    - |
      # frozen_string_literal: true

  :subject:
    - |
      "Hello " + "%{string}"

  :contexts:
    -
      :string:
        - Alice
        - Bob

  :actuals:
    - |
      "%{subject}.length"
    - |
      "%{subject}.to_s"

actuals:
  - "%{subject}.blank_line"
  - "%{subject}.context_names"
  - "%{subject}.test_params"
  - "%{subject}.to_s"
