AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

  # @see https://docs.rubocop.org/rubocop/configuration.html#pre-processing
  Exclude:
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-performance-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-rake-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-thread-safety-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-yml
  
    - .yardoc/
  
    - coverage/
  
    - doc/
  
    - pkg/
  
    - test.rb
    - examples/**/*

inherit_from:
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/performance.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/rake.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/thread_safety.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-gitlab-security
  - rubocop-md
