require:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  Exclude:
    - test.rb
    - examples/**/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
