---
header: |
  begin
    require_relative 'greeter'
  rescue ::LoadError
    require './greeter'
  end

front_object: |
  Greeter

subject: |
  %{front_object}.new(%{string})

variables:
  :string:
    - "'world'"

actual_values:
  - "%{subject}.salute"
