---
header: |
  begin
    require_relative 'greeter'
  rescue ::LoadError
    require './greeter'
  end

subject: |
  Greeter.new(%{string})

contexts:
  :string:
    - "'world'"

actuals:
  - "%{subject}.salute"
